
export const SET_TYPE_OF_MOVIE_CONSTANT = "SET_TYPE_OF_MOVIE_CONSTANT";

export const SET_INFOR_LIST_SEARCH_CONSTANT = "SET_INFOR_LIST_SEARCH_CONSTANT";

export const SET_INFOR_SEARCH_CONSTANT = "SET_INFOR_SEARCH_CONSTANT";

export const SET_CURRENT_PAGE_CONSTANT = "SET_CURRENT_PAGE_CONSTANT";

