

export const SET_INFOR_LIST_MOVIE_CONSTANT = "SET_INFOR_LIST_MOVIE_CONSTANT";

export const SET_INFOR_SEARCH_CONSTANT = "SET_INFOR_SEARCH_CONSTANT";

export const SET_BOOK_TICKET_PROGRESS_CONSTANT = "SET_BOOK_TICKET_PROGRESS_CONSTANT";

export const SET_DETAIL_ORDER_CONSTANT = "SET_DETAIL_ORDER_CONSTANT";