

export const SET_INFOR_SEARCH_CONSTANT = "SET_INFOR_SEARCH_CONSTANT";

export const SET_INFOR_LIST_ORDER_CONSTANT = "SET_INFOR_LIST_ORDER_CONSTANT";

export const SET_ORDER_STATUS_CONSTANT = "SET_ORDER_STATUS_CONSTANT";