spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 20
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 283263190878-ednkm73ltsu83cnctnjsj269qgvihqce.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile
              - email
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secretKey: "d3775c0fefb657b49d334eacae493726e131ea10e36b9f8800185b05d210ddd4"
domain:
  fe: "http://localhost:9999"
  be: ${DOMAIN_BE}
app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:9999/oauth2/redirect
server:
  port: 8080
