
export const SET_LIST_STAFF_CONSTANT = "SET_LIST_STAFF_CONSTANT";

export const SET_SEARCH_VALUE_CONSTANT = "SET_SEARCH_VALUE_CONSTANT";

export const SET_DETAIL_STAFF_CONSTANT = "SET_DETAIL_STAFF_CONSTANT";

export const SET_TOTAL_ELEMENT_CONSTANT = "SET_TOTAL_ELEMENT_CONSTANT";
